services:
  - type: web
    name: pizzeria-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://pizzeria-frontend-mwio.onrender.com
        sync: false
      - key: RATE_LIMIT_MAX
        value: 300
      - key: DATABASE_URL
        sync: false

  - type: static_site
    name: pizzeria-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - path: /
      - path: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://pizzeria-backend-i7y2.onrender.com/api
        sync: false
